apiVersion: v1
kind: Secret
metadata:
  name: dbt-demo-redshift
  labels:
    app.kubernetes.io/name: dbt-demo
    app.kubernetes.io/part-of: analytics-platform
type: Opaque
stringData:
  DBT_TARGET: prod
  REDSHIFT_HOST: replace-me
  REDSHIFT_PORT: "5439"
  REDSHIFT_DATABASE: analytics
  REDSHIFT_SCHEMA: analytics
  REDSHIFT_USER: replace-me
  REDSHIFT_PASSWORD: replace-me
  REDSHIFT_SSLMODE: require
  DB_THREADS: "4"
