apiVersion: v1
kind: Secret
metadata:
  name: dbt-demo-db
  labels:
    app.kubernetes.io/name: dbt-demo
    app.kubernetes.io/part-of: analytics-platform
type: Opaque
stringData:
  DBT_TARGET: prod
  DB_HOST: replace-me
  DB_PORT: "5432"
  DB_NAME: replace-me
  DB_SCHEMA: analytics
  DB_USER: replace-me
  DB_PASSWORD: replace-me
  DB_THREADS: "4"
