apiVersion: v1
kind: ServiceAccount
metadata:
  name: dbt-demo
  labels:
    app.kubernetes.io/name: dbt-demo
    app.kubernetes.io/part-of: analytics-platform
imagePullSecrets:
  - name: dbt-demo-ecr-pull
automountServiceAccountToken: false
